'use strict';
const $=s=>document.querySelector(s);
const ui={dictionary:$('#dictionary'),volume:$('#volume'),bottomDictionary:$('#bottomDictionary'),bottomVolume:$('#bottomVolume'),page:$('#page'),faces:$('#faces'),toc:$('#toc'),position:$('#position'),source:$('#source'),notice:$('#notice'),sidebar:$('#sidebar'),scrim:$('#scrim')};
const rows=Array.isArray(window.KOJISHO_DATA)?window.KOJISHO_DATA:[];
const dictionaryOrder=['天治本新撰字鏡','寛政版本草和名','高山寺本和名類聚抄','元和版和名類聚抄','箋注和名類聚抄','図書寮本類聚名義抄','観智院本類聚名義抄','前田本色葉字類抄','黒川本色葉字類抄'];
let current=[],activeRow=null,currentPid='',currentFrame=1,maxFrame=Infinity,lastGood=null;
const viewer=OpenSeadragon({id:'viewer',showNavigationControl:false,animationTime:.35,blendTime:.15,maxZoomPixelRatio:4,visibilityRatio:.5,constrainDuringPan:true,gestureSettingsMouse:{clickToZoom:false,dblClickToZoom:false,scrollToZoom:true},gestureSettingsTouch:{pinchToZoom:true,pinchRotate:false,clickToZoom:false,dblClickToZoom:false}});
const unique=a=>[...new Set(a)];
const natural=(a,b)=>String(a).localeCompare(String(b),'ja',{numeric:true});
const key=r=>[r['辞書名'],r['巻'],r['頁'],r['面']].join('|');

function frame(row){const m=row?.URL.match(/pid\/(\d+)\/(\d+)/);return m?{pid:m[1],number:Number(m[2])}:null}
function dictionaryNames(){const found=unique(rows.map(r=>r['辞書名']));return [...dictionaryOrder.filter(n=>found.includes(n)),...found.filter(n=>!dictionaryOrder.includes(n))]}
function volumeCompare(a,b){if(/^\d+$/.test(a)&&/^\d+$/.test(b))return Number(a)-Number(b);const rank={'仏':0,'法':1,'僧':2,'上':0,'中':1,'下':2,'本':0,'末':1},aa=[...String(a)],bb=[...String(b)],length=Math.max(aa.length,bb.length);for(let i=0;i<length;i++){const ar=aa[i]===undefined?-1:(rank[aa[i]]??9),br=bb[i]===undefined?-1:(rank[bb[i]]??9);if(ar!==br)return ar-br}return natural(a,b)}
function setOptions(el,values,selected,label=String){el.replaceChildren(...values.map(value=>Object.assign(document.createElement('option'),{value,textContent:label(value),selected:value===selected})))}
function volumesFor(dict){return unique(rows.filter(r=>r['辞書名']===dict).map(r=>r['巻'])).sort(volumeCompare)}
function syncDictionaryOptions(selected){const names=dictionaryNames();setOptions(ui.dictionary,names,selected);setOptions(ui.bottomDictionary,names,selected)}
function syncVolumeOptions(dict,selected){const volumes=volumesFor(dict),value=volumes.includes(selected)?selected:volumes[0];setOptions(ui.volume,volumes,value,v=>v||'なし');setOptions(ui.bottomVolume,volumes,value,v=>v||'なし');return value}
function selectDictionary(name,reset=false){const names=dictionaryNames(),selected=names.includes(name)?name:names[0];syncDictionaryOptions(selected);const volumes=volumesFor(selected),wanted=reset?volumes[0]:(localStorage.getItem('kojisho.volume')||volumes[0]),volume=syncVolumeOptions(selected,wanted);selectVolume(volume,'',reset)}
function selectVolume(value,preferredKey='',reset=false){ui.volume.value=value;ui.bottomVolume.value=value;current=rows.filter(r=>r['辞書名']===ui.dictionary.value&&r['巻']===value).sort((a,b)=>natural(a['頁'],b['頁'])||natural(a['面'],b['面']));const saved=preferredKey||localStorage.getItem('kojisho.key'),firstPage=current[0]?.['頁'],row=reset?(current.find(r=>r['頁']===firstPage&&r['面']==='オ')||current[0]):(current.find(r=>key(r)===saved)||current[0]);buildToc();if(row)showRow(row)}
function buildToc(filter=''){const pages=unique(current.map(r=>r['頁'])).filter(p=>!filter||String(p).includes(filter));ui.toc.replaceChildren(...pages.map(page=>{const b=document.createElement('button');b.textContent=page;b.dataset.page=page;b.onclick=()=>{showRow(current.find(r=>r['頁']===page));closeSidebar()};return b}))}
function renderFaceButtons(faceRows,selectedRow){ui.faces.hidden=false;ui.faces.replaceChildren(...['オ','ウ'].map(face=>{const faceRow=faceRows.find(r=>r['面']===face),b=document.createElement('button');b.textContent=face;b.disabled=!faceRow;b.className=faceRow&&selectedRow&&key(faceRow)===key(selectedRow)?'active':'';if(faceRow)b.onclick=()=>showRow(faceRow);return b}))}
function iiifInfo(pid,n){return`https://www.dl.ndl.go.jp/api/iiif/${pid}/R${String(n).padStart(7,'0')}/info.json`}
function sourceUrl(pid,n){return`https://dl.ndl.go.jp/pid/${pid}/1/${n}`}
function rowsAtFrame(pid,n){return rows.filter(row=>{const f=frame(row);return f&&f.pid===pid&&f.number===n})}
function positionText(row){const f=frame(row);if(!f)return row['辞書名'];const mapped=rowsAtFrame(f.pid,f.number).filter(r=>r['辞書名']===row['辞書名']),locations=[];for(const item of mapped){const location={volume:item['巻'],page:`${item['頁']}${item['面']==='なし'?'':item['面']}`};if(!locations.some(x=>x.volume===location.volume&&x.page===location.page))locations.push(location)}if(!locations.length)return row['辞書名'];const first=locations[0],parts=[first.volume,first.page].filter(Boolean).join('・');const rest=locations.slice(1).map(item=>item.volume===first.volume?item.page:[item.volume,item.page].filter(Boolean).join('・'));return`${row['辞書名']}・${[parts,...rest].join('／')}`}
async function findFrameLimit(pid){maxFrame=Infinity;try{const response=await fetch(`https://www.dl.ndl.go.jp/api/iiif/${pid}/manifest.json`);if(!response.ok)return;const matches=JSON.stringify(await response.json()).match(/R(\d{7})/g)||[];if(matches.length)maxFrame=Math.max(...matches.map(v=>Number(v.slice(1))))}catch(_){/* 取得失敗時は画像の有無で判定する */}}
function renderFrame(pid,n){currentPid=pid;currentFrame=n;ui.source.href=sourceUrl(pid,n);ui.notice.hidden=false;ui.notice.textContent='読み込み中';viewer.open(iiifInfo(pid,n))}
function showRow(row){if(!row)return;const locationChanged=!activeRow||activeRow['辞書名']!==row['辞書名']||activeRow['巻']!==row['巻'];activeRow=row;syncDictionaryOptions(row['辞書名']);const volume=syncVolumeOptions(row['辞書名'],row['巻']);ui.volume.value=volume;current=rows.filter(r=>r['辞書名']===row['辞書名']&&r['巻']===row['巻']).sort((a,b)=>natural(a['頁'],b['頁'])||natural(a['面'],b['面']));if(locationChanged)buildToc($('#pageSearch').value.trim());const pages=unique(current.map(r=>r['頁']));setOptions(ui.page,pages,row['頁']);const faces=current.filter(r=>r['頁']===row['頁']);renderFaceButtons(faces,row);ui.position.textContent=positionText(row);[...ui.toc.children].forEach(b=>b.classList.toggle('active',b.dataset.page===row['頁']));localStorage.setItem('kojisho.dictionary',row['辞書名']);localStorage.setItem('kojisho.volume',row['巻']);localStorage.setItem('kojisho.key',key(row));const f=frame(row);if(f){if(f.pid!==currentPid)findFrameLimit(f.pid);renderFrame(f.pid,f.number)}}
function moveFrame(delta){const target=currentFrame+delta;if(target<1||target>maxFrame)return;const mapped=rowsAtFrame(currentPid,target);if(mapped.length){const same=mapped.filter(r=>r['辞書名']===ui.dictionary.value),choices=same.length?same:mapped;showRow(delta>0?choices[0]:choices[choices.length-1])}else{activeRow=null;ui.position.textContent=`${ui.dictionary.value}・コマ${target}`;renderFaceButtons([],null);ui.page.selectedIndex=-1;renderFrame(currentPid,target)}}
function openSidebar(){ui.sidebar.classList.add('open');ui.scrim.classList.add('open');$('#menu').setAttribute('aria-expanded','true');$('#menu').setAttribute('aria-label','目次を閉じる')}
function closeSidebar(){ui.sidebar.classList.remove('open');ui.scrim.classList.remove('open');$('#menu').setAttribute('aria-expanded','false');$('#menu').setAttribute('aria-label','目次を開く')}
function toggleSidebar(){ui.sidebar.classList.contains('open')?closeSidebar():openSidebar()}
function applyTheme(theme){document.documentElement.dataset.theme=theme;const toggle=$('#themeToggle'),dark=theme==='dark',color=dark?'#17140f':'#f3efe5',old=$('#themeColor'),meta=old.cloneNode();meta.content=color;old.replaceWith(meta);document.documentElement.style.backgroundColor=color;toggle.textContent=dark?'☀':'☾';toggle.setAttribute('aria-label',dark?'ライトモードに切り替える':'ダークモードに切り替える')}

viewer.addHandler('open',()=>{viewer.viewport.goHome(true);ui.notice.hidden=true;lastGood={pid:currentPid,number:currentFrame}});
viewer.addHandler('open-failed',()=>{ui.notice.hidden=false;ui.notice.textContent='このコマの画像を表示できない';if(!Number.isFinite(maxFrame)&&lastGood&&currentFrame>lastGood.number){maxFrame=lastGood.number;currentFrame=lastGood.number}});
function flashEdge(selector){const hint=$(selector);hint.classList.remove('flash');requestAnimationFrame(()=>hint.classList.add('flash'));setTimeout(()=>hint.classList.remove('flash'),220)}
viewer.addHandler('canvas-click',event=>{if(!event.quick)return;const width=viewer.container.clientWidth;if(event.position.x<=width/8){flashEdge('.edge-next');moveFrame(1)}else if(event.position.x>=width*7/8){flashEdge('.edge-previous');moveFrame(-1)}});
ui.dictionary.onchange=()=>selectDictionary(ui.dictionary.value,true);ui.bottomDictionary.onchange=()=>selectDictionary(ui.bottomDictionary.value,true);ui.volume.onchange=()=>selectVolume(ui.volume.value,'',true);ui.bottomVolume.onchange=()=>selectVolume(ui.bottomVolume.value,'',true);ui.page.onchange=()=>showRow(current.find(r=>r['頁']===ui.page.value));
$('#pageSearch').oninput=e=>buildToc(e.target.value.trim());
function setFullscreenState(fullscreen){document.body.classList.toggle('viewer-fullscreen',fullscreen);$('#fullscreen').setAttribute('aria-label',fullscreen?'全画面を終了':'全画面')}
$('#zoomIn').onclick=()=>viewer.viewport.zoomBy(1.3);$('#zoomOut').onclick=()=>viewer.viewport.zoomBy(1/1.3);$('#home').onclick=()=>viewer.viewport.goHome();$('#fullscreen').onclick=()=>viewer.setFullScreen(!viewer.isFullPage());$('#exitFullscreen').onclick=()=>viewer.setFullScreen(false);viewer.addHandler('full-screen',event=>setFullscreenState(event.fullScreen));
$('#viewer').addEventListener('pointermove',event=>{const rect=event.currentTarget.getBoundingClientRect(),x=event.clientX-rect.left;event.currentTarget.dataset.edge=x<=rect.width/8?'left':x>=rect.width*7/8?'right':''});$('#viewer').addEventListener('pointerleave',event=>delete event.currentTarget.dataset.edge);
$('#menu').onclick=toggleSidebar;$('#close').onclick=closeSidebar;ui.scrim.onclick=closeSidebar;document.addEventListener('dblclick',e=>e.preventDefault(),{passive:false});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeSidebar();if(e.key==='ArrowLeft')moveFrame(1);if(e.key==='ArrowRight')moveFrame(-1)});
const savedTheme=localStorage.getItem('kojisho.theme'),systemTheme=matchMedia('(prefers-color-scheme: light)').matches?'light':'dark';applyTheme(savedTheme||systemTheme);$('#themeToggle').onclick=()=>{const next=document.documentElement.dataset.theme==='dark'?'light':'dark';localStorage.setItem('kojisho.theme',next);applyTheme(next)};
if(rows.length){const savedDictionary=localStorage.getItem('kojisho.dictionary');selectDictionary(savedDictionary||'観智院本類聚名義抄',!savedDictionary)}else ui.notice.textContent='古辞書データを読み込めない';
if('serviceWorker'in navigator&&location.protocol.startsWith('http'))window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js'));
