'use strict';
const $=s=>document.querySelector(s);
const ui={dictionary:$('#dictionary'),volume:$('#volume'),bottomDictionary:$('#bottomDictionary'),bottomVolume:$('#bottomVolume'),sidebarPage:$('#sidebarPage'),page:$('#page'),sidebarFaces:$('#sidebarFaces'),faces:$('#faces'),desktopHeading:$('#desktopPositionHeading'),desktopDetail:$('#desktopPositionDetail'),mobileHeading:$('#mobilePositionHeading'),mobileDetail:$('#mobilePositionDetail'),source:$('#source'),notice:$('#notice'),sidebar:$('#sidebar'),scrim:$('#scrim'),popover:$('#locationPopover'),locationToggle:$('#locationToggle')};
const rows=Array.isArray(window.KOJISHO_DATA)?window.KOJISHO_DATA:[];
const dictionaryOrder=['天治本新撰字鏡','寛政版本草和名','高山寺本和名類聚抄','元和版和名類聚抄','箋注和名類聚抄','図書寮本類聚名義抄','観智院本類聚名義抄','前田本色葉字類抄','黒川本色葉字類抄'];
let current=[],activeRow=null,currentPid='',currentFrame=1,maxFrame=Infinity,lastGood=null;
const viewer=OpenSeadragon({id:'viewer',showNavigationControl:false,animationTime:.35,blendTime:.15,maxZoomPixelRatio:4,visibilityRatio:.5,constrainDuringPan:true,gestureSettingsMouse:{clickToZoom:false,dblClickToZoom:false,scrollToZoom:true},gestureSettingsTouch:{pinchToZoom:true,pinchRotate:false,clickToZoom:false,dblClickToZoom:false}});
const unique=a=>[...new Set(a)];
const natural=(a,b)=>String(a).localeCompare(String(b),'ja',{numeric:true});
const key=r=>[r['辞書名'],r['巻'],r['頁'],r['面']].join('|');

function frame(row){const m=row?.URL.match(/pid\/(\d+)\/(\d+)/);return m?{pid:m[1],number:Number(m[2])}:null}
function frameHash(pid,n){return`#/pid/${pid}/1/${n}`}
function parseFrameHash(){const match=location.hash.match(/^#\/pid\/(\d+)\/1\/(\d+)$/),number=Number(match?.[2]);return match&&number>0?{pid:match[1],number}:null}
function updateFrameHash(pid,n){const hash=frameHash(pid,n);if(location.hash!==hash)history.replaceState(null,'',hash)}
function dictionaryNames(){const found=unique(rows.map(r=>r['辞書名']));return [...dictionaryOrder.filter(n=>found.includes(n)),...found.filter(n=>!dictionaryOrder.includes(n))]}
function volumeLabel(value){return /^\d+$/.test(value)?`巻${value}`:(value||'なし')}
function volumeCompare(a,b){if(/^\d+$/.test(a)&&/^\d+$/.test(b))return Number(a)-Number(b);const rank={'仏':0,'法':1,'僧':2,'上':0,'中':1,'下':2,'本':0,'末':1},aa=[...String(a)],bb=[...String(b)],length=Math.max(aa.length,bb.length);for(let i=0;i<length;i++){const ar=aa[i]===undefined?-1:(rank[aa[i]]??9),br=bb[i]===undefined?-1:(rank[bb[i]]??9);if(ar!==br)return ar-br}return natural(a,b)}
function setOptions(el,values,selected,label=String){el.replaceChildren(...values.map(value=>Object.assign(document.createElement('option'),{value,textContent:label(value),selected:value===selected})))}
function volumesFor(dict){return unique(rows.filter(r=>r['辞書名']===dict).map(r=>r['巻'])).sort(volumeCompare)}
function syncDictionaryOptions(selected){const names=dictionaryNames();for(const select of[ui.dictionary,ui.bottomDictionary])setOptions(select,names,selected)}
function syncVolumeOptions(dict,selected){const volumes=volumesFor(dict),value=volumes.includes(selected)?selected:volumes[0];for(const select of[ui.volume,ui.bottomVolume])setOptions(select,volumes,value,volumeLabel);return value}
function syncPageOptions(selected){const pages=unique(current.map(r=>r['頁']));for(const select of[ui.sidebarPage,ui.page])setOptions(select,pages,selected);return pages}
function selectDictionary(name,reset=false){const names=dictionaryNames(),selected=names.includes(name)?name:names[0];syncDictionaryOptions(selected);const volumes=volumesFor(selected),wanted=reset?volumes[0]:(localStorage.getItem('kojisho.volume')||volumes[0]),volume=syncVolumeOptions(selected,wanted);selectVolume(volume,'',reset)}
function selectVolume(value,preferredKey='',reset=false){ui.volume.value=value;ui.bottomVolume.value=value;current=rows.filter(r=>r['辞書名']===ui.dictionary.value&&r['巻']===value).sort((a,b)=>natural(a['頁'],b['頁'])||natural(a['面'],b['面']));const saved=preferredKey||localStorage.getItem('kojisho.key'),firstPage=current[0]?.['頁'],row=reset?(current.find(r=>r['頁']===firstPage&&r['面']==='オ')||current[0]):(current.find(r=>key(r)===saved)||current[0]);if(row)showRow(row)}
function preferredFaceRow(pageRows){return pageRows.find(r=>r['面']==='オ')||pageRows[0]}
function normalizedLocation(value){return value.normalize('NFKC').replace(/[ー－‐‑‒–—―−]/g,'-').replace(/[\s・]/g,'').toLowerCase()}
function parseLocation(value,dict,currentVolume){const query=normalizedLocation(value),faceMatch=query.match(/(オ|お|o|a|ウ|う|b)$/),face=faceMatch&&/[オおoa]/.test(faceMatch[1])?'オ':faceMatch?'ウ':'オ',body=faceMatch?query.slice(0,-faceMatch[1].length):query,numeric=body.match(/^(\d+)-(\d+)$/);if(numeric)return{volume:numeric[1],page:numeric[2],face,faceSpecified:!!faceMatch};if(/^\d+$/.test(body))return{volume:currentVolume,page:body,face,faceSpecified:!!faceMatch};const volumes=volumesFor(dict).filter(v=>v&&!/^\d+$/.test(v)).sort((a,b)=>normalizedLocation(b).length-normalizedLocation(a).length),matched=volumes.find(v=>body.startsWith(normalizedLocation(v)));return matched?{volume:matched,page:body.slice(normalizedLocation(matched).length),face,faceSpecified:!!faceMatch}:null}
function rowForLocation(value,dict,currentVolume){const location=parseLocation(value,dict,currentVolume);if(!location||!/^\d+$/.test(location.page))return null;const candidates=rows.filter(r=>r['辞書名']===dict&&r['巻']===location.volume&&normalizedLocation(r['頁'])===location.page),hasFaces=candidates.some(r=>r['面']==='オ'||r['面']==='ウ');if(!hasFaces)return candidates[0]||null;return candidates.find(r=>r['面']===location.face)||(!location.faceSpecified?preferredFaceRow(candidates):null)}
function openLocation(value){const error=$('#locationError');error.textContent='';if(!normalizedLocation(value)){error.textContent='位置を入力';return}const row=rowForLocation(value,ui.dictionary.value,ui.volume.value);if(!row){error.textContent='該当なし';return}showRow(row);$('#locationQuery').value='';closeMobileSidebar()}
function openBottomLocation(value){const input=$('#bottomLocationQuery'),error=$('#bottomLocationError');input.setAttribute('aria-invalid','false');error.textContent='';if(!normalizedLocation(value))return;const row=rowForLocation(value,ui.bottomDictionary.value,ui.bottomVolume.value);if(!row){input.setAttribute('aria-invalid','true');error.textContent='該当なし';return}showRow(row);input.value='';closeLocationPopover()}
function renderFaceGroup(container,faceRows,selectedRow,afterSelect){container.replaceChildren(...['オ','ウ'].map(face=>{const faceRow=faceRows.find(r=>r['面']===face),button=document.createElement('button');button.type='button';button.textContent=face;button.disabled=!faceRow;button.className=faceRow&&selectedRow&&key(faceRow)===key(selectedRow)?'active':'';button.setAttribute('aria-pressed',String(button.className==='active'));if(faceRow)button.onclick=()=>{showRow(faceRow);afterSelect()};return button}))}
function renderFaceButtons(faceRows,selectedRow){renderFaceGroup(ui.sidebarFaces,faceRows,selectedRow,closeMobileSidebar);renderFaceGroup(ui.faces,faceRows,selectedRow,closeLocationPopover)}
function iiifInfo(pid,n){return`https://www.dl.ndl.go.jp/api/iiif/${pid}/R${String(n).padStart(7,'0')}/info.json`}
function sourceUrl(pid,n){return`https://dl.ndl.go.jp/pid/${pid}/1/${n}`}
function rowsAtFrame(pid,n){return rows.filter(row=>{const f=frame(row);return f&&f.pid===pid&&f.number===n})}
function locationsAtRow(row){const f=frame(row);if(!f)return[];const locations=[];for(const item of rowsAtFrame(f.pid,f.number).filter(r=>r['辞書名']===row['辞書名'])){const location={volume:item['巻'],page:`${item['頁']}${item['面']==='なし'?'':item['面']}`};if(!locations.some(x=>x.volume===location.volume&&x.page===location.page))locations.push(location)}return locations}
function positionParts(row){const locations=locationsAtRow(row).reverse();if(!locations.length)return{heading:row['辞書名'],detail:'NA'};const sameVolume=locations.every(item=>item.volume===locations[0].volume);if(sameVolume)return{heading:[row['辞書名'],locations[0].volume?volumeLabel(locations[0].volume):''].filter(Boolean).join('・'),detail:locations.map(item=>item.page).join('｜')};return{heading:row['辞書名'],detail:locations.map(item=>[item.volume?volumeLabel(item.volume):'',item.page].filter(Boolean).join('・')).join('｜')}}
function setPositionDisplay(heading,detail){for(const [headingNode,detailNode] of[[ui.desktopHeading,ui.desktopDetail],[ui.mobileHeading,ui.mobileDetail]]){headingNode.textContent=heading;detailNode.textContent=detail}}
function updatePosition(row){const position=positionParts(row);setPositionDisplay(position.heading,position.detail)}
async function findFrameLimit(pid){maxFrame=Infinity;try{const response=await fetch(`https://www.dl.ndl.go.jp/api/iiif/${pid}/manifest.json`);if(!response.ok)return;const matches=JSON.stringify(await response.json()).match(/R(\d{7})/g)||[];if(matches.length)maxFrame=Math.max(...matches.map(v=>Number(v.slice(1))))}catch(_){/* 取得失敗時は画像の有無で判定する */}}
function renderFrame(pid,n){currentPid=pid;currentFrame=n;updateFrameHash(pid,n);ui.source.href=sourceUrl(pid,n);ui.notice.hidden=false;ui.notice.textContent='読み込み中';viewer.open(iiifInfo(pid,n))}
function showRow(row){if(!row)return;activeRow=row;syncDictionaryOptions(row['辞書名']);const volume=syncVolumeOptions(row['辞書名'],row['巻']);ui.volume.value=volume;current=rows.filter(r=>r['辞書名']===row['辞書名']&&r['巻']===row['巻']).sort((a,b)=>natural(a['頁'],b['頁'])||natural(a['面'],b['面']));syncPageOptions(row['頁']);const faces=current.filter(r=>r['頁']===row['頁']);renderFaceButtons(faces,row);updatePosition(row);localStorage.setItem('kojisho.dictionary',row['辞書名']);localStorage.setItem('kojisho.volume',row['巻']);localStorage.setItem('kojisho.key',key(row));const f=frame(row);if(f){if(f.pid!==currentPid)findFrameLimit(f.pid);renderFrame(f.pid,f.number)}}
function showUnmappedFrame(pid,target,dictionary=ui.dictionary.value){activeRow=null;setPositionDisplay(dictionary,'NA');renderFaceButtons([],null);for(const select of[ui.sidebarPage,ui.page])select.selectedIndex=-1;renderFrame(pid,target)}
function openFrameLink(pid,target){const registered=rows.filter(row=>frame(row)?.pid===pid);if(!registered.length){viewer.close();activeRow=null;currentPid='';ui.source.removeAttribute('href');setPositionDisplay('未登録の資料','');ui.notice.hidden=false;ui.notice.textContent='この資料は古辞書ビューワーに登録されていない';return}const savedDictionary=localStorage.getItem('kojisho.dictionary'),mapped=rowsAtFrame(pid,target),row=mapped.find(item=>item['辞書名']===savedDictionary)||mapped[0];if(row){showRow(row);return}const representative=registered.find(item=>item['辞書名']===savedDictionary)||registered[0];syncDictionaryOptions(representative['辞書名']);const volume=syncVolumeOptions(representative['辞書名'],representative['巻']);ui.volume.value=volume;current=rows.filter(item=>item['辞書名']===representative['辞書名']&&item['巻']===volume).sort((a,b)=>natural(a['頁'],b['頁'])||natural(a['面'],b['面']));syncPageOptions('');findFrameLimit(pid);showUnmappedFrame(pid,target,representative['辞書名'])}
function moveFrame(delta){const target=currentFrame+delta;if(target<1||target>maxFrame)return;const mapped=rowsAtFrame(currentPid,target);if(mapped.length){const same=mapped.filter(r=>r['辞書名']===ui.dictionary.value),choices=same.length?same:mapped;showRow(delta>0?choices[0]:choices[choices.length-1])}else showUnmappedFrame(currentPid,target)}
function setHomeZoomFloor(){const viewport=viewer.viewport,home=viewport.getHomeZoom();if(Number.isFinite(home)&&home>0){viewport.minZoomLevel=home;viewport.applyConstraints(true)}}
function resetViewAfterLayout(){requestAnimationFrame(()=>requestAnimationFrame(()=>{setHomeZoomFloor();viewer.viewport.goHome(true)}))}
function preserveViewAfterLayout(){const item=viewer.world.getItemAt(0);if(!item){resetViewAfterLayout();return}const viewport=viewer.viewport,center=item.viewportToImageCoordinates(viewport.getCenter()),zoom=item.viewportToImageZoom(viewport.getZoom());requestAnimationFrame(()=>requestAnimationFrame(()=>{setHomeZoomFloor();const targetCenter=item.imageToViewportCoordinates(center),targetZoom=item.imageToViewportZoom(zoom);viewport.zoomTo(Math.max(targetZoom,viewport.getHomeZoom()),targetCenter,true);viewport.panTo(targetCenter,true);viewport.applyConstraints(true)}))}
const mobileSidebar=matchMedia('(max-width:768px)');
function setLocationPopoverOpen(open){ui.popover.hidden=!open;ui.locationToggle.setAttribute('aria-expanded',String(open));ui.locationToggle.classList.toggle('active',open)}
function closeLocationPopover(){setLocationPopoverOpen(false)}
function setSidebarExpanded(expanded){$('#menu').setAttribute('aria-expanded',String(expanded))}
function closeMobileSidebar(){const wasOpen=ui.sidebar.classList.contains('open');ui.sidebar.classList.remove('open');ui.scrim.classList.remove('open');if(mobileSidebar.matches)setSidebarExpanded(false);if(wasOpen)resetViewAfterLayout()}
function toggleSidebar(){closeLocationPopover();if(mobileSidebar.matches){const open=!ui.sidebar.classList.contains('open');ui.sidebar.classList.toggle('open',open);ui.scrim.classList.toggle('open',open);setSidebarExpanded(open)}else{const collapsed=!$('main').classList.contains('sidebar-collapsed');$('main').classList.toggle('sidebar-collapsed',collapsed);setSidebarExpanded(!collapsed)}resetViewAfterLayout()}
function syncSidebarMode(){ui.sidebar.classList.remove('open');ui.scrim.classList.remove('open');closeLocationPopover();setSidebarExpanded(!mobileSidebar.matches&&!$('main').classList.contains('sidebar-collapsed'))}
const themeIcons={sun:'<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="3.5"/><path d="M12 2.5v2M12 19.5v2M2.5 12h2M19.5 12h2M5.3 5.3l1.4 1.4M17.3 17.3l1.4 1.4M18.7 5.3l-1.4 1.4M6.7 17.3l-1.4 1.4"/></svg>',moon:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M20 15.2A8.5 8.5 0 0 1 8.8 4a8.5 8.5 0 1 0 11.2 11.2Z"/></svg>'};
const fullscreenIcons={enter:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M8 3H3v5M16 3h5v5M21 16v5h-5M3 16v5h5"/></svg>',exit:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M9 3v6H3M15 3v6h6M21 15h-6v6M3 15h6v6"/></svg>'};
function applyTheme(theme){document.documentElement.dataset.theme=theme;const toggle=$('#themeToggle'),dark=theme==='dark',color=dark?'#212121':'#ffffff',old=$('#themeColor'),meta=old.cloneNode();meta.content=color;old.replaceWith(meta);document.documentElement.style.backgroundColor=color;toggle.innerHTML=dark?themeIcons.sun:themeIcons.moon;toggle.setAttribute('aria-label',dark?'ライトモードに切り替える':'ダークモードに切り替える')}

viewer.addHandler('open',()=>{viewer.viewport.minZoomLevel=viewer.viewport.getHomeZoom();viewer.viewport.goHome(true);ui.notice.hidden=true;lastGood={pid:currentPid,number:currentFrame}});
viewer.addHandler('resize',setHomeZoomFloor);
viewer.addHandler('open-failed',()=>{ui.notice.hidden=false;ui.notice.textContent='このコマの画像を表示できない';if(!Number.isFinite(maxFrame)&&lastGood&&currentFrame>lastGood.number){maxFrame=lastGood.number;currentFrame=lastGood.number}});
function flashEdge(selector){const hint=$(selector);hint.classList.remove('flash');requestAnimationFrame(()=>hint.classList.add('flash'));setTimeout(()=>hint.classList.remove('flash'),220)}
viewer.addHandler('canvas-click',event=>{if(!event.quick)return;const width=viewer.container.clientWidth;if(event.position.x<=width/8){flashEdge('.edge-next');moveFrame(1)}else if(event.position.x>=width*7/8){flashEdge('.edge-previous');moveFrame(-1)}});
ui.dictionary.onchange=()=>selectDictionary(ui.dictionary.value,true);ui.bottomDictionary.onchange=()=>selectDictionary(ui.bottomDictionary.value,true);ui.volume.onchange=()=>selectVolume(ui.volume.value,'',true);ui.bottomVolume.onchange=()=>selectVolume(ui.bottomVolume.value,'',true);
ui.sidebarPage.onchange=()=>{showRow(preferredFaceRow(current.filter(r=>r['頁']===ui.sidebarPage.value)));closeMobileSidebar()};
ui.page.onchange=()=>{showRow(preferredFaceRow(current.filter(r=>r['頁']===ui.page.value)));closeLocationPopover()};
$('#locationSearch').onsubmit=e=>{e.preventDefault();openLocation($('#locationQuery').value)};
$('#locationQuery').onkeydown=e=>{if(e.key==='Enter'&&!e.isComposing){e.preventDefault();$('#locationSearch').requestSubmit()}};
$('#locationQuery').oninput=()=>$('#locationError').textContent='';
$('#bottomLocationSearch').onsubmit=e=>{e.preventDefault();openBottomLocation($('#bottomLocationQuery').value)};
$('#bottomLocationQuery').onkeydown=e=>{if(e.key==='Enter'&&!e.isComposing){e.preventDefault();$('#bottomLocationSearch').requestSubmit()}};
$('#bottomLocationQuery').oninput=e=>{e.currentTarget.setAttribute('aria-invalid','false');$('#bottomLocationError').textContent=''};
function setFullscreenState(fullscreen){const button=$('#fullscreen'),label=fullscreen?'全画面表示を終了':'全画面表示';document.body.classList.toggle('viewer-fullscreen',fullscreen);closeMobileSidebar();closeLocationPopover();button.innerHTML=fullscreen?fullscreenIcons.exit:fullscreenIcons.enter;button.setAttribute('aria-label',label);button.dataset.tooltip=label;button.setAttribute('aria-pressed',String(fullscreen));preserveViewAfterLayout()}
$('#zoomIn').onclick=()=>{viewer.viewport.zoomBy(1.3);viewer.viewport.applyConstraints()};$('#zoomOut').onclick=()=>{viewer.viewport.zoomBy(1/1.3);viewer.viewport.applyConstraints()};$('#home').onclick=()=>viewer.viewport.goHome();$('#fullscreen').onclick=()=>setFullscreenState(!document.body.classList.contains('viewer-fullscreen'));$('#exitFullscreen').onclick=()=>setFullscreenState(false);
$('#viewer').addEventListener('pointermove',event=>{const rect=event.currentTarget.getBoundingClientRect(),x=event.clientX-rect.left;event.currentTarget.dataset.edge=x<=rect.width/8?'left':x>=rect.width*7/8?'right':''});$('#viewer').addEventListener('pointerleave',event=>delete event.currentTarget.dataset.edge);
const inputHelpDialog=$('#inputHelpDialog');for(const button of[$('#sidebarHelpToggle'),$('#popoverHelpToggle')])button.onclick=()=>inputHelpDialog.showModal();$('#inputHelpClose').onclick=()=>inputHelpDialog.close();inputHelpDialog.onclick=event=>{if(event.target===inputHelpDialog)inputHelpDialog.close()};
$('#menu').onclick=toggleSidebar;ui.locationToggle.onclick=()=>setLocationPopoverOpen(ui.popover.hidden);$('#resetApp').onclick=()=>{if(mobileSidebar.matches&&ui.sidebar.classList.contains('open')){closeMobileSidebar();return}selectDictionary('観智院本類聚名義抄',true);resetViewAfterLayout()};ui.scrim.onclick=closeMobileSidebar;document.addEventListener('pointerdown',event=>{if(!ui.popover.hidden&&!ui.popover.contains(event.target)&&!ui.locationToggle.contains(event.target))closeLocationPopover()});document.addEventListener('dblclick',e=>e.preventDefault(),{passive:false});document.addEventListener('keydown',e=>{if(e.key==='Escape'){if(inputHelpDialog.open){inputHelpDialog.close();return}if(document.body.classList.contains('viewer-fullscreen'))setFullscreenState(false);else{closeMobileSidebar();closeLocationPopover()}}if(e.key==='ArrowLeft')moveFrame(1);if(e.key==='ArrowRight')moveFrame(-1)});
document.addEventListener('pointerup',event=>{if(event.pointerType==='touch')event.target.closest('button,a')?.blur()});
const toolbar=$('.tools');let tooltipTimer=0,tooltipTarget=null,tooltipWarm=false;
function hideTooltip(reset=false){clearTimeout(tooltipTimer);tooltipTarget?.classList.remove('show-tooltip');tooltipTarget=null;if(reset)tooltipWarm=false}
function showTooltip(target,delay){clearTimeout(tooltipTimer);tooltipTimer=setTimeout(()=>{hideTooltip();tooltipTarget=target;target.classList.add('show-tooltip');tooltipWarm=true},delay)}
toolbar.addEventListener('pointerover',event=>{if(event.pointerType==='touch')return;const target=event.target.closest('[data-tooltip]');if(target&&toolbar.contains(target))showTooltip(target,tooltipWarm?100:450)});
toolbar.addEventListener('pointerout',event=>{const target=event.target.closest('[data-tooltip]');if(!target||target.contains(event.relatedTarget))return;hideTooltip(!toolbar.contains(event.relatedTarget))});
toolbar.addEventListener('focusin',event=>{const target=event.target.closest('[data-tooltip]');if(target){hideTooltip();tooltipTarget=target;target.classList.add('show-tooltip')}});
toolbar.addEventListener('focusout',event=>{if(!toolbar.contains(event.relatedTarget))hideTooltip(true);else hideTooltip()});
toolbar.addEventListener('click',()=>hideTooltip(true));
const savedTheme=localStorage.getItem('kojisho.theme');applyTheme(savedTheme||'dark');$('#themeToggle').onclick=()=>{const next=document.documentElement.dataset.theme==='dark'?'light':'dark';localStorage.setItem('kojisho.theme',next);applyTheme(next)};
mobileSidebar.addEventListener('change',syncSidebarMode);syncSidebarMode();if(rows.length){const linkedFrame=parseFrameHash();if(linkedFrame)openFrameLink(linkedFrame.pid,linkedFrame.number);else{const savedDictionary=localStorage.getItem('kojisho.dictionary');selectDictionary(savedDictionary||'観智院本類聚名義抄',!savedDictionary)}}else ui.notice.textContent='古辞書データを読み込めない';
window.addEventListener('hashchange',()=>{const linkedFrame=parseFrameHash();if(linkedFrame&&(linkedFrame.pid!==currentPid||linkedFrame.number!==currentFrame))openFrameLink(linkedFrame.pid,linkedFrame.number)});
if('serviceWorker'in navigator&&location.protocol.startsWith('http'))window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js?v=42',{updateViaCache:'none'}));
