'use strict';
const $=s=>document.querySelector(s);
const ui={dictionary:$('#dictionary'),volume:$('#volume'),bottomDictionary:$('#bottomDictionary'),bottomVolume:$('#bottomVolume'),page:$('#page'),faces:$('#faces'),toc:$('#toc'),position:$('#position'),mobilePosition:$('#mobilePosition'),mobileLocationSummary:$('#mobileLocationSummary'),source:$('#source'),notice:$('#notice'),sidebar:$('#sidebar'),scrim:$('#scrim'),pager:$('.pager')};
const rows=Array.isArray(window.KOJISHO_DATA)?window.KOJISHO_DATA:[];
const dictionaryOrder=['天治本新撰字鏡','寛政版本草和名','高山寺本和名類聚抄','元和版和名類聚抄','箋注和名類聚抄','図書寮本類聚名義抄','観智院本類聚名義抄','前田本色葉字類抄','黒川本色葉字類抄'];
let current=[],activeRow=null,currentPid='',currentFrame=1,maxFrame=Infinity,lastGood=null;
const viewer=OpenSeadragon({id:'viewer',showNavigationControl:false,animationTime:.35,blendTime:.15,maxZoomPixelRatio:4,visibilityRatio:.5,constrainDuringPan:true,gestureSettingsMouse:{clickToZoom:false,dblClickToZoom:false,scrollToZoom:true},gestureSettingsTouch:{pinchToZoom:true,pinchRotate:false,clickToZoom:false,dblClickToZoom:false}});
const unique=a=>[...new Set(a)];
const natural=(a,b)=>String(a).localeCompare(String(b),'ja',{numeric:true});
const key=r=>[r['辞書名'],r['巻'],r['頁'],r['面']].join('|');

function frame(row){const m=row?.URL.match(/pid\/(\d+)\/(\d+)/);return m?{pid:m[1],number:Number(m[2])}:null}
function frameHash(pid,n){return`#/pid/${pid}/1/${n}`}
function parseFrameHash(){const match=location.hash.match(/^#\/pid\/(\d+)\/1\/(\d+)$/),number=Number(match?.[2]);return match&&number>0?{pid:match[1],number}:null}
function updateFrameHash(pid,n){const hash=frameHash(pid,n);if(location.hash!==hash)history.replaceState(null,'',hash)}
function dictionaryNames(){const found=unique(rows.map(r=>r['辞書名']));return [...dictionaryOrder.filter(n=>found.includes(n)),...found.filter(n=>!dictionaryOrder.includes(n))]}
function volumeCompare(a,b){if(/^\d+$/.test(a)&&/^\d+$/.test(b))return Number(a)-Number(b);const rank={'仏':0,'法':1,'僧':2,'上':0,'中':1,'下':2,'本':0,'末':1},aa=[...String(a)],bb=[...String(b)],length=Math.max(aa.length,bb.length);for(let i=0;i<length;i++){const ar=aa[i]===undefined?-1:(rank[aa[i]]??9),br=bb[i]===undefined?-1:(rank[bb[i]]??9);if(ar!==br)return ar-br}return natural(a,b)}
function setOptions(el,values,selected,label=String){el.replaceChildren(...values.map(value=>Object.assign(document.createElement('option'),{value,textContent:label(value),selected:value===selected})))}
function volumesFor(dict){return unique(rows.filter(r=>r['辞書名']===dict).map(r=>r['巻'])).sort(volumeCompare)}
function syncDictionaryOptions(selected){const names=dictionaryNames();setOptions(ui.dictionary,names,selected);setOptions(ui.bottomDictionary,names,selected)}
function syncVolumeOptions(dict,selected){const volumes=volumesFor(dict),value=volumes.includes(selected)?selected:volumes[0];setOptions(ui.volume,volumes,value,v=>v||'なし');setOptions(ui.bottomVolume,volumes,value,v=>v||'なし');return value}
function selectDictionary(name,reset=false){const names=dictionaryNames(),selected=names.includes(name)?name:names[0];syncDictionaryOptions(selected);const volumes=volumesFor(selected),wanted=reset?volumes[0]:(localStorage.getItem('kojisho.volume')||volumes[0]),volume=syncVolumeOptions(selected,wanted);selectVolume(volume,'',reset)}
function selectVolume(value,preferredKey='',reset=false){ui.volume.value=value;ui.bottomVolume.value=value;current=rows.filter(r=>r['辞書名']===ui.dictionary.value&&r['巻']===value).sort((a,b)=>natural(a['頁'],b['頁'])||natural(a['面'],b['面']));const saved=preferredKey||localStorage.getItem('kojisho.key'),firstPage=current[0]?.['頁'],row=reset?(current.find(r=>r['頁']===firstPage&&r['面']==='オ')||current[0]):(current.find(r=>key(r)===saved)||current[0]);buildToc();if(row)showRow(row)}
function preferredFaceRow(pageRows){return pageRows.find(r=>r['面']==='オ')||pageRows[0]}
function buildToc(){const pages=unique(current.map(r=>r['頁']));ui.toc.replaceChildren(...pages.map(page=>{const b=document.createElement('button');b.textContent=page;b.dataset.page=page;b.onclick=()=>{showRow(preferredFaceRow(current.filter(r=>r['頁']===page)));closeMobileSidebar()};return b}))}
function normalizedLocation(value){return value.normalize('NFKC').replace(/[\s・]/g,'').toLowerCase()}
function parseLocation(value,dict,currentVolume){const query=normalizedLocation(value),faceMatch=query.match(/(オ|お|o|a|ウ|う|b)$/),face=faceMatch&&/[オおoa]/.test(faceMatch[1])?'オ':faceMatch?'ウ':'オ',body=faceMatch?query.slice(0,-faceMatch[1].length):query,numeric=body.match(/^(\d+)-(\d+)$/);if(numeric)return{volume:numeric[1],page:numeric[2],face,faceSpecified:!!faceMatch};if(/^\d+$/.test(body))return{volume:currentVolume,page:body,face,faceSpecified:!!faceMatch};const volumes=volumesFor(dict).filter(v=>v&&!/^\d+$/.test(v)).sort((a,b)=>normalizedLocation(b).length-normalizedLocation(a).length),matched=volumes.find(v=>body.startsWith(normalizedLocation(v)));return matched?{volume:matched,page:body.slice(normalizedLocation(matched).length),face,faceSpecified:!!faceMatch}:null}
function rowForLocation(value,dict,currentVolume){const location=parseLocation(value,dict,currentVolume);if(!location||!/^\d+$/.test(location.page))return null;const candidates=rows.filter(r=>r['辞書名']===dict&&r['巻']===location.volume&&normalizedLocation(r['頁'])===location.page);return candidates.find(r=>r['面']===location.face)||(!location.faceSpecified?preferredFaceRow(candidates):null)}
function openLocation(value){const error=$('#locationError');error.textContent='';if(!normalizedLocation(value)){error.textContent='巻・頁・面を入力';return}const row=rowForLocation(value,ui.dictionary.value,ui.volume.value);if(!row){error.textContent='該当する位置がない';return}showRow(row);$('#locationQuery').value='';closeMobileSidebar()}
function openBottomLocation(value){const input=$('#bottomLocationQuery');input.setAttribute('aria-invalid','false');if(!normalizedLocation(value))return;const row=rowForLocation(value,ui.bottomDictionary.value,ui.bottomVolume.value);if(!row){input.setAttribute('aria-invalid','true');return}showRow(row);input.value=''}
function renderFaceButtons(faceRows,selectedRow){ui.faces.hidden=false;ui.faces.replaceChildren(...['オ','ウ'].map(face=>{const faceRow=faceRows.find(r=>r['面']===face),b=document.createElement('button');b.textContent=face;b.disabled=!faceRow;b.className=faceRow&&selectedRow&&key(faceRow)===key(selectedRow)?'active':'';if(faceRow)b.onclick=()=>{showRow(faceRow);closeMobileLocation()};return b}))}
function iiifInfo(pid,n){return`https://www.dl.ndl.go.jp/api/iiif/${pid}/R${String(n).padStart(7,'0')}/info.json`}
function sourceUrl(pid,n){return`https://dl.ndl.go.jp/pid/${pid}/1/${n}`}
function rowsAtFrame(pid,n){return rows.filter(row=>{const f=frame(row);return f&&f.pid===pid&&f.number===n})}
function locationsAtRow(row){const f=frame(row);if(!f)return[];const locations=[];for(const item of rowsAtFrame(f.pid,f.number).filter(r=>r['辞書名']===row['辞書名'])){const location={volume:item['巻'],page:`${item['頁']}${item['面']==='なし'?'':item['面']}`};if(!locations.some(x=>x.volume===location.volume&&x.page===location.page))locations.push(location)}return locations}
function locationListText(locations){if(!locations.length)return'';const first=locations[0],parts=[first.volume,first.page].filter(Boolean).join('・'),rest=locations.slice(1).map(item=>item.volume===first.volume?item.page:[item.volume,item.page].filter(Boolean).join('・'));return[parts,...rest].join('／')}
function positionText(row){const locations=locationsAtRow(row);return locations.length?`${row['辞書名']}・${locationListText(locations)}`:row['辞書名']}
async function findFrameLimit(pid){maxFrame=Infinity;try{const response=await fetch(`https://www.dl.ndl.go.jp/api/iiif/${pid}/manifest.json`);if(!response.ok)return;const matches=JSON.stringify(await response.json()).match(/R(\d{7})/g)||[];if(matches.length)maxFrame=Math.max(...matches.map(v=>Number(v.slice(1))))}catch(_){/* 取得失敗時は画像の有無で判定する */}}
function renderFrame(pid,n){currentPid=pid;currentFrame=n;updateFrameHash(pid,n);ui.source.href=sourceUrl(pid,n);ui.notice.hidden=false;ui.notice.textContent='読み込み中';viewer.open(iiifInfo(pid,n))}
function updateMobileLocation(row){const face=row['面']==='なし'?'':row['面'],locations=locationsAtRow(row),short=locationListText(locations)||[row['巻'],`${row['頁']}${face}`].filter(Boolean).join('・');ui.mobilePosition.textContent=short;ui.mobileLocationSummary.textContent=[row['辞書名'],row['巻'],row['頁'],face].filter(Boolean).join('　')}
function showRow(row){if(!row)return;const locationChanged=!activeRow||activeRow['辞書名']!==row['辞書名']||activeRow['巻']!==row['巻'];activeRow=row;syncDictionaryOptions(row['辞書名']);const volume=syncVolumeOptions(row['辞書名'],row['巻']);ui.volume.value=volume;current=rows.filter(r=>r['辞書名']===row['辞書名']&&r['巻']===row['巻']).sort((a,b)=>natural(a['頁'],b['頁'])||natural(a['面'],b['面']));if(locationChanged)buildToc();const pages=unique(current.map(r=>r['頁']));setOptions(ui.page,pages,row['頁']);const faces=current.filter(r=>r['頁']===row['頁']);renderFaceButtons(faces,row);ui.position.textContent=positionText(row);updateMobileLocation(row);[...ui.toc.children].forEach(b=>b.classList.toggle('active',b.dataset.page===row['頁']));localStorage.setItem('kojisho.dictionary',row['辞書名']);localStorage.setItem('kojisho.volume',row['巻']);localStorage.setItem('kojisho.key',key(row));const f=frame(row);if(f){if(f.pid!==currentPid)findFrameLimit(f.pid);renderFrame(f.pid,f.number)}}
function showUnmappedFrame(pid,target,dictionary=ui.dictionary.value){activeRow=null;const frameText=`${target}コマ目`;ui.position.textContent=`${dictionary}・${frameText}`;ui.mobilePosition.textContent=frameText;ui.mobileLocationSummary.textContent=`${dictionary}　${frameText}`;renderFaceButtons([],null);ui.page.selectedIndex=-1;renderFrame(pid,target)}
function openFrameLink(pid,target){const registered=rows.filter(row=>frame(row)?.pid===pid);if(!registered.length){viewer.close();activeRow=null;currentPid='';ui.source.removeAttribute('href');ui.position.textContent='未登録の資料';ui.mobilePosition.textContent='未登録の資料';ui.mobileLocationSummary.textContent='この資料は古辞書ビューワーに登録されていない';ui.notice.hidden=false;ui.notice.textContent='この資料は古辞書ビューワーに登録されていない';return}const savedDictionary=localStorage.getItem('kojisho.dictionary'),mapped=rowsAtFrame(pid,target),row=mapped.find(item=>item['辞書名']===savedDictionary)||mapped[0];if(row){showRow(row);return}const representative=registered.find(item=>item['辞書名']===savedDictionary)||registered[0];syncDictionaryOptions(representative['辞書名']);const volume=syncVolumeOptions(representative['辞書名'],representative['巻']);ui.volume.value=volume;current=rows.filter(item=>item['辞書名']===representative['辞書名']&&item['巻']===volume).sort((a,b)=>natural(a['頁'],b['頁'])||natural(a['面'],b['面']));buildToc();findFrameLimit(pid);showUnmappedFrame(pid,target,representative['辞書名'])}
function moveFrame(delta){const target=currentFrame+delta;if(target<1||target>maxFrame)return;const mapped=rowsAtFrame(currentPid,target);if(mapped.length){const same=mapped.filter(r=>r['辞書名']===ui.dictionary.value),choices=same.length?same:mapped;showRow(delta>0?choices[0]:choices[choices.length-1])}else showUnmappedFrame(currentPid,target)}
function setHomeZoomFloor(){const viewport=viewer.viewport,home=viewport.getHomeZoom();if(Number.isFinite(home)&&home>0){viewport.minZoomLevel=home;viewport.applyConstraints(true)}}
function resetViewAfterLayout(){requestAnimationFrame(()=>requestAnimationFrame(()=>{setHomeZoomFloor();viewer.viewport.goHome(true)}))}
const mobileSidebar=matchMedia('(max-width:768px)');
const phoneFullscreen=matchMedia('(max-width:600px), (max-height:600px) and (pointer:coarse)');
function setMobileLocationOpen(open){ui.pager.classList.toggle('open',open);$('#mobileLocationToggle').setAttribute('aria-expanded',String(open));if(open)$('#mobileLocationClose').focus()}
function closeMobileLocation(){if(mobileSidebar.matches&&ui.pager.classList.contains('open')){setMobileLocationOpen(false);$('#mobileLocationToggle').focus({preventScroll:true})}}
function setSidebarExpanded(expanded){$('#menu').setAttribute('aria-expanded',String(expanded))}
function closeMobileSidebar(){const wasOpen=ui.sidebar.classList.contains('open');ui.sidebar.classList.remove('open');ui.scrim.classList.remove('open');if(mobileSidebar.matches)setSidebarExpanded(false);if(wasOpen)resetViewAfterLayout()}
function toggleSidebar(){if(mobileSidebar.matches){closeMobileLocation();const open=!ui.sidebar.classList.contains('open');ui.sidebar.classList.toggle('open',open);ui.scrim.classList.toggle('open',open);setSidebarExpanded(open)}else{const collapsed=!$('main').classList.contains('sidebar-collapsed');$('main').classList.toggle('sidebar-collapsed',collapsed);setSidebarExpanded(!collapsed)}resetViewAfterLayout()}
function syncSidebarMode(){ui.sidebar.classList.remove('open');ui.scrim.classList.remove('open');ui.pager.classList.remove('open');$('#mobileLocationToggle').setAttribute('aria-expanded','false');setSidebarExpanded(!mobileSidebar.matches&&!$('main').classList.contains('sidebar-collapsed'))}
const themeIcons={sun:'<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="3.5"/><path d="M12 2.5v2M12 19.5v2M2.5 12h2M19.5 12h2M5.3 5.3l1.4 1.4M17.3 17.3l1.4 1.4M18.7 5.3l-1.4 1.4M6.7 17.3l-1.4 1.4"/></svg>',moon:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M20 15.2A8.5 8.5 0 0 1 8.8 4a8.5 8.5 0 1 0 11.2 11.2Z"/></svg>'};
const fullscreenIcons={enter:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M8 3H3v5M16 3h5v5M21 16v5h-5M3 16v5h5"/></svg>',exit:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M9 3v6H3M15 3v6h6M21 15h-6v6M3 15h6v6"/></svg>'};
function applyTheme(theme){document.documentElement.dataset.theme=theme;const toggle=$('#themeToggle'),dark=theme==='dark',color=dark?'#212121':'#ffffff',old=$('#themeColor'),meta=old.cloneNode();meta.content=color;old.replaceWith(meta);document.documentElement.style.backgroundColor=color;toggle.innerHTML=dark?themeIcons.sun:themeIcons.moon;toggle.setAttribute('aria-label',dark?'ライトモードに切り替える':'ダークモードに切り替える')}

viewer.addHandler('open',()=>{viewer.viewport.minZoomLevel=viewer.viewport.getHomeZoom();viewer.viewport.goHome(true);ui.notice.hidden=true;lastGood={pid:currentPid,number:currentFrame}});
viewer.addHandler('resize',setHomeZoomFloor);
viewer.addHandler('open-failed',()=>{ui.notice.hidden=false;ui.notice.textContent='このコマの画像を表示できない';if(!Number.isFinite(maxFrame)&&lastGood&&currentFrame>lastGood.number){maxFrame=lastGood.number;currentFrame=lastGood.number}});
function flashEdge(selector){const hint=$(selector);hint.classList.remove('flash');requestAnimationFrame(()=>hint.classList.add('flash'));setTimeout(()=>hint.classList.remove('flash'),220)}
viewer.addHandler('canvas-click',event=>{if(!event.quick)return;const width=viewer.container.clientWidth;if(event.position.x<=width/8){flashEdge('.edge-next');moveFrame(1)}else if(event.position.x>=width*7/8){flashEdge('.edge-previous');moveFrame(-1)}});
ui.dictionary.onchange=()=>selectDictionary(ui.dictionary.value,true);ui.bottomDictionary.onchange=()=>selectDictionary(ui.bottomDictionary.value,true);ui.volume.onchange=()=>selectVolume(ui.volume.value,'',true);ui.bottomVolume.onchange=()=>selectVolume(ui.bottomVolume.value,'',true);ui.page.onchange=()=>{showRow(preferredFaceRow(current.filter(r=>r['頁']===ui.page.value)));closeMobileLocation()};
$('#locationSearch').onsubmit=e=>{e.preventDefault();openLocation($('#locationQuery').value)};
$('#locationQuery').oninput=()=>$('#locationError').textContent='';
$('#bottomLocationSearch').onsubmit=e=>{e.preventDefault();const input=$('#bottomLocationQuery'),before=input.value;openBottomLocation(before);if(before&&!input.value)closeMobileLocation()};
$('#bottomLocationQuery').onkeydown=e=>{if(e.key==='Enter'&&!e.isComposing){e.preventDefault();$('#bottomLocationSearch').requestSubmit()}};
$('#bottomLocationQuery').oninput=e=>e.currentTarget.setAttribute('aria-invalid','false');
function setFullscreenState(fullscreen){const button=$('#fullscreen');document.body.classList.toggle('viewer-fullscreen',fullscreen);if(!fullscreen)document.documentElement.classList.remove('mobile-fullscreen');button.innerHTML=fullscreen?fullscreenIcons.exit:fullscreenIcons.enter;button.setAttribute('aria-label',fullscreen?'全画面を終了':'全画面');button.setAttribute('aria-pressed',String(fullscreen))}
$('#zoomIn').onclick=()=>{viewer.viewport.zoomBy(1.3);viewer.viewport.applyConstraints()};$('#zoomOut').onclick=()=>{viewer.viewport.zoomBy(1/1.3);viewer.viewport.applyConstraints()};$('#home').onclick=()=>viewer.viewport.goHome();$('#fullscreen').onclick=()=>{const entering=!viewer.isFullPage();if(entering&&phoneFullscreen.matches)document.documentElement.classList.add('mobile-fullscreen');viewer.setFullScreen(entering)};$('#exitFullscreen').onclick=()=>viewer.setFullScreen(false);viewer.addHandler('full-screen',event=>setFullscreenState(event.fullScreen));
$('#viewer').addEventListener('pointermove',event=>{const rect=event.currentTarget.getBoundingClientRect(),x=event.clientX-rect.left;event.currentTarget.dataset.edge=x<=rect.width/8?'left':x>=rect.width*7/8?'right':''});$('#viewer').addEventListener('pointerleave',event=>delete event.currentTarget.dataset.edge);
$('#menu').onclick=toggleSidebar;$('#mobileLocationToggle').onclick=()=>setMobileLocationOpen(!ui.pager.classList.contains('open'));$('#mobileLocationClose').onclick=closeMobileLocation;$('#mobileLocationScrim').onclick=closeMobileLocation;$('#resetApp').onclick=()=>{selectDictionary('観智院本類聚名義抄',true);resetViewAfterLayout()};ui.scrim.onclick=closeMobileSidebar;document.addEventListener('dblclick',e=>e.preventDefault(),{passive:false});document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeMobileSidebar();closeMobileLocation()}if(e.key==='ArrowLeft')moveFrame(1);if(e.key==='ArrowRight')moveFrame(-1)});
const savedTheme=localStorage.getItem('kojisho.theme');applyTheme(savedTheme||'dark');$('#themeToggle').onclick=()=>{const next=document.documentElement.dataset.theme==='dark'?'light':'dark';localStorage.setItem('kojisho.theme',next);applyTheme(next)};
mobileSidebar.addEventListener('change',syncSidebarMode);syncSidebarMode();if(rows.length){const linkedFrame=parseFrameHash();if(linkedFrame)openFrameLink(linkedFrame.pid,linkedFrame.number);else{const savedDictionary=localStorage.getItem('kojisho.dictionary');selectDictionary(savedDictionary||'観智院本類聚名義抄',!savedDictionary)}}else ui.notice.textContent='古辞書データを読み込めない';
window.addEventListener('hashchange',()=>{const linkedFrame=parseFrameHash();if(linkedFrame&&(linkedFrame.pid!==currentPid||linkedFrame.number!==currentFrame))openFrameLink(linkedFrame.pid,linkedFrame.number)});
if('serviceWorker'in navigator&&location.protocol.startsWith('http'))window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js?v=42',{updateViaCache:'none'}));
